version: "3.9"

services:
  movie_web:
    build: lab2
    image: nginx_lab
    container_name:
      movie_nginx
    volumes:
      - ./lab2/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - movie_api
    networks:
      - movies_nginx_network
    restart: on-failure

  movie_api:
    build: simple_API
    image: movie_api_v1
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080 --access-log
    volumes:
      - ./simple_API/app/:/app/
    expose:
      - 8080
    depends_on:
      - movie_db
    env_file:
      - simple_API/.env
    deploy:
      mode: replicated
      replicas: 3
    networks:
      movies_db_network:
      movies_nginx_network:
    restart: on-failure

  movie_db:
    image: postgres:12.1-alpine
    container_name:
      movie_db
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    env_file:
      - simple_API/.env.db
    networks:
      - movies_db_network
    restart: on-failure

  service_1:
    build: lab2/service_1
    image: service_1
    container_name:
      service_1
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8081
    volumes:
      - ./lab2/service_1/app/:/app/
    ports:
      - 8081:8081
    networks:
      movies_nginx_network:
    restart: on-failure

  service_2:
    build: lab2/service_2
    image: service_2
    container_name:
      service_2
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8082
    volumes:
      - ./lab2/service_2/app/:/app/
    ports:
      - 8082:8082
    networks:
      movies_nginx_network:
    restart: on-failure

volumes:
  postgres_data_movie:
networks:
  movies_db_network:
    driver: bridge
  movies_nginx_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.224.0/24
          gateway: 192.168.224.1

