version: '3.7'

services:
  movie_service:
    build: .
    container_name:
      movie_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --access-log
    volumes:
      - ./:/app/
    ports:
      - 8001:8000
    env_file:
      - .env
    networks:
      - movies_db_network
      - movies_nginx_network

  movie_db:
    image: postgres:12.1-alpine
    container_name:
      movie_db
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    env_file:
      - .env.db
    networks:
      - movies_db_network

volumes:
  postgres_data_movie:
networks:
  movies_db_network:
    driver: bridge
  movies_nginx_network:
    driver: bridge
